apiVersion: v1
kind: Service
metadata:
  name: portfolio-nodeport-service
spec:
  selector:
    app: portfolio
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30007
  type: NodePort 
